//! Compare Rust classification on real vert12S data against R/C baseline.
//!
//! The baseline was generated by R/C IDTAXA (reference/c_source + reference/r_source)
//! on the 1K benchmark dataset (1000 reference sequences, 500 queries) with
//! default parameters (threshold=60, bootstraps=100, strand=both, seed=42).
//!
//! Rust's batch fraction learning intentionally diverges from R's sequential
//! approach. Documented path agreement: 87-93% on benchmark data. This test
//! catches regressions beyond the known divergence.

use oxidtaxa::classify::id_taxa;
use oxidtaxa::fasta::{read_fasta, read_taxonomy};
use oxidtaxa::sequence::remove_gaps;
use oxidtaxa::training::learn_taxa;
use oxidtaxa::types::{ClassifyConfig, OutputType, StrandMode, TrainConfig};

#[derive(serde::Deserialize)]
struct BaselineEntry {
    path: String,
    confidence: f64,
}

#[derive(serde::Deserialize)]
struct Baseline {
    n_queries: usize,
    problem_sequences: usize,
    problem_groups: usize,
    results: Vec<BaselineEntry>,
}

#[test]
fn test_baseline_1k_matches_r() {
    let manifest_dir = std::path::PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    let data_dir = manifest_dir.join("benchmarks").join("data");
    let baseline_path = manifest_dir
        .join("benchmarks")
        .join("baselines")
        .join("baseline_1k.json");

    // Skip if benchmark data isn't present
    if !data_dir.join("bench_1000_ref.fasta").exists() {
        eprintln!("Skipping baseline_1k test: benchmark data not found");
        return;
    }

    // Load baseline
    let baseline_content = std::fs::read_to_string(&baseline_path)
        .unwrap_or_else(|e| panic!("Cannot read baseline: {}", e));
    let baseline: Baseline = serde_json::from_str(&baseline_content)
        .unwrap_or_else(|e| panic!("Cannot parse baseline: {}", e));

    // Read reference data
    let (ref_names, ref_seqs) =
        read_fasta(data_dir.join("bench_1000_ref.fasta").to_str().unwrap()).unwrap();
    let ref_tax =
        read_taxonomy(data_dir.join("bench_1000_ref_taxonomy.tsv").to_str().unwrap(), &ref_names)
            .unwrap();

    // Filter for training (same as eval_training.rs and train_idtaxa.R)
    let mut train_seqs = Vec::new();
    let mut train_tax = Vec::new();
    for (i, seq) in ref_seqs.iter().enumerate() {
        let tax = &ref_tax[i];
        let full_tax = format!("Root; {}", tax.replace(";", "; "));
        let rank_count = full_tax.split("; ").count();
        if rank_count < 4 || seq.len() < 30 {
            continue;
        }
        let n_count = seq.bytes().filter(|&b| b == b'N' || b == b'n').count();
        if (n_count as f64 / seq.len() as f64) > 0.3 {
            continue;
        }
        train_seqs.push(seq.clone());
        train_tax.push(full_tax);
    }

    // Train
    let train_config = TrainConfig::default();
    let model = learn_taxa(&train_seqs, &train_tax, &train_config, 42, false).unwrap();

    // Read and classify queries
    let (query_names, query_seqs) =
        read_fasta(data_dir.join("bench_1000_query.fasta").to_str().unwrap()).unwrap();
    let clean_queries = remove_gaps(&query_seqs);

    let classify_config = ClassifyConfig::default();
    let results = id_taxa(
        &clean_queries,
        &query_names,
        &model,
        &classify_config,
        StrandMode::Both,
        OutputType::Extended,
        42,
        true, // deterministic
    );

    // Compare against R baseline
    assert_eq!(
        results.len(),
        baseline.n_queries,
        "query count mismatch: got {}, baseline {}",
        results.len(),
        baseline.n_queries
    );

    let mut path_mismatches = 0usize;
    let mut max_conf_diff: f64 = 0.0;
    let mut total_conf_diff: f64 = 0.0;

    for (i, result) in results.iter().enumerate() {
        let gold = &baseline.results[i];

        // Extract path: skip Root, filter unclassified_ ranks
        let rust_path = {
            let mut taxa = result.taxon.clone();
            if taxa.len() > 1 {
                taxa.remove(0); // skip Root
            }
            taxa.into_iter()
                .filter(|t| !t.starts_with("unclassified_"))
                .collect::<Vec<_>>()
                .join(";")
        };

        // Extract confidence: min of non-Root ranks
        let rust_conf = if result.confidence.len() > 1 {
            result.confidence[1..]
                .iter()
                .cloned()
                .fold(f64::INFINITY, f64::min)
        } else {
            0.0
        };

        if rust_path != gold.path {
            path_mismatches += 1;
        }

        let diff = (rust_conf - gold.confidence).abs();
        total_conf_diff += diff;
        if diff > max_conf_diff {
            max_conf_diff = diff;
        }
    }

    let n = results.len() as f64;
    let path_agreement = 100.0 * (results.len() - path_mismatches) as f64 / n;
    let mean_conf_diff = total_conf_diff / n;

    eprintln!("Baseline 1K results:");
    eprintln!("  Path agreement:      {:.1}% ({} mismatches out of {})", path_agreement, path_mismatches, results.len());
    eprintln!("  Mean confidence diff: {:.2}", mean_conf_diff);
    eprintln!("  Max confidence diff:  {:.2}", max_conf_diff);
    eprintln!("  Problem seqs:  rust={}, R={}", model.problem_sequences.len(), baseline.problem_sequences);
    eprintln!("  Problem groups: rust={}, R={}", model.problem_groups.len(), baseline.problem_groups);

    // Thresholds account for known batch-training divergence from R's sequential
    // approach (documented 87-93% path agreement). These catch regressions beyond
    // the expected divergence without requiring exact R replication.
    assert!(
        path_agreement >= 85.0,
        "Path agreement {:.1}% < 85% threshold ({} mismatches) — \
         below documented batch-training divergence range",
        path_agreement,
        path_mismatches
    );
    assert!(
        mean_conf_diff < 5.0,
        "Mean confidence diff {:.2} >= 5.0 threshold",
        mean_conf_diff
    );
    assert!(
        max_conf_diff < 30.0,
        "Max confidence diff {:.2} >= 30.0 threshold",
        max_conf_diff
    );
}
